baseURL: 'http://herbstation.github.io/'
languageCode: 'en-us'
title: '35 Below Archive'
theme: 'hugo-xmin'
copyright: 'Copyright Â© 2025, 35 Below Team'
params:
    logo: /pix/welcome.png

taxonomies:
    category: categories
    tag: tags
    contributor: contributors

markup:
    goldmark:
        renderer:
            hardWraps: true
            unsafe: true

menu:
    main:
    -   identifier: contributors
        name: Contribution Credits
        url: /contributors/
        weight: 1
    -   identifier: art
        name: Official Art
        url: /art/
        weight: 2
    -   identifier: fanart
        name: Fan Art
        url: /fanart/
        weight: 3
    -   identifier: roundRecordings
        name: Round Recordings
        url: /rounds/
        weight: 3
    -   identifier: tags
        name: Tags
        url: /tags/
        weight: 4